# Generated by Django 3.1.6 on 2021-02-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='abc',
            field=models.BooleanField(default=False),
        ),
    ]
