# Generated by Django 3.1.6 on 2021-02-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_account_abc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='abc',
        ),
    ]
