# Generated by Django 3.1.6 on 2021-02-06 07:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_remove_account_abc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('instructions', models.TextField()),
                ('password', models.CharField(max_length=120)),
                ('start_date', models.DateTimeField(verbose_name='start time')),
                ('end_date', models.DateTimeField(verbose_name='end time')),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'quiz',
            },
        ),
    ]
