# Generated by Django 3.1.6 on 2021-02-06 09:16

from django.db import migrations, models
import quiz_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(default=quiz_app.models.Quiz.default_end_datetime, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='instructions',
            field=models.TextField(default='Instructions here'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(default=quiz_app.models.Quiz.default_start_datetime, verbose_name='start time'),
        ),
    ]
